services:
  js-react-web-frontend-template:
    container_name: js-react-web-frontend-template
    build:
      context: .
    ports:
      - '${FRONTEND_APP_PORT:-5000}:5000'
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./.env:/usr/src/app/.env
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
